version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests -Pcodedeploy
      # this is per this advice here: https://docs.aws.amazon.com/codepipeline/latest/userguide/troubleshooting.html#troubleshooting-aeb2
      - mv target/ROOT ./
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - mvn package
artifacts:
  files:
    - ROOT/**/*
  discard-paths: yes
