version: 0.2

phases:
  build:
    commands:
      - echo Build and unit tests started on `date`
      - mvn package surefire:test -PHSQLDB
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - mvn package
reports: #New
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports 